# SLO: 99% of game actions ACKed within 250ms
groups:
  - name: game-action-ack-latency-slo
    rules:
      - record: game_action_ack_latency_ms:sli_latency:ratio_rate1h
        expr: sum(rate(game_action_ack_latency_ms_bucket{le="250"}[1h]))
          / sum(rate(game_action_ack_latency_ms_count[1h]))
      - record: game_action_ack_latency_ms:sli_latency:ratio_rate6h
        expr: sum(rate(game_action_ack_latency_ms_bucket{le="250"}[6h]))
          / sum(rate(game_action_ack_latency_ms_count[6h]))
      - record: game_action_ack_latency_error_budget_burn_rate_1h
        expr: (1 - game_action_ack_latency_ms:sli_latency:ratio_rate1h) / (1 - 0.99)
      - record: game_action_ack_latency_error_budget_burn_rate_6h
        expr: (1 - game_action_ack_latency_ms:sli_latency:ratio_rate6h) / (1 - 0.99)
  - name: game-action-ack-latency-alerts
    rules:
      - alert: GameActionAckLatencySLOBurnRate1h
        expr: game_action_ack_latency_error_budget_burn_rate_1h > 14.4
        for: 2m
        labels:
          severity: critical
          pagerduty_service: pokerhub-ops
        annotations:
          summary: "1h game action ACK latency burn rate too high"
      - alert: GameActionAckLatencySLOBurnRate6h
        expr: game_action_ack_latency_error_budget_burn_rate_6h > 6
        for: 15m
        labels:
          severity: critical
          pagerduty_service: pokerhub-ops
        annotations:
          summary: "6h game action ACK latency burn rate too high"
