# Alert when WebSocket outbound queues back up
---
groups:
  - name: ws-outbound-queue-alerts
    rules:
      - alert: WsOutboundQueueThresholdExceeded
        expr: max(ws_outbound_queue_depth) > max(ws_outbound_queue_threshold)
        for: 2m
        labels:
          severity: warning
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "WebSocket outbound queue depth above threshold"
      - alert: WsOutboundQueueLimitExceeded
        expr: max(ws_outbound_queue_depth) > max(ws_outbound_queue_limit)
        for: 1m
        labels:
          severity: critical
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "WebSocket outbound queue depth exceeded limit"

