route:
  group_by: ['alertname']
  receiver: 'null'
  routes:
    - matchers:
        - pagerduty_service=~".+"
      receiver: pagerduty
receivers:
  - name: 'null'
  - name: pagerduty
    pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        severity: '{{ .CommonLabels.severity }}'
        component: '{{ .CommonLabels.pagerduty_service }}'
