# SLO: 99% of game actions ACKed within 250ms
groups:
  - name: game-action-ack-latency-quantiles
    rules:
      - record: game_action_ack_latency_ms:p50
        expr: histogram_quantile(0.5,
          sum(rate(game_action_ack_latency_ms_bucket[5m])) by (le))
      - record: game_action_ack_latency_ms:p95
        expr: histogram_quantile(0.95,
          sum(rate(game_action_ack_latency_ms_bucket[5m])) by (le))
      - record: game_action_ack_latency_ms:p99
        expr: histogram_quantile(0.99,
          sum(rate(game_action_ack_latency_ms_bucket[5m])) by (le))
  - name: game-action-ack-latency-slo
    rules:
      - record: game_action_ack_latency_ms:sli_latency:ratio_rate5m
        expr: sum(rate(game_action_ack_latency_ms_bucket{le="250"}[5m]))
          / sum(rate(game_action_ack_latency_ms_count[5m]))
      - record: game_action_ack_latency_ms:sli_latency:ratio_rate30m
        expr: sum(rate(game_action_ack_latency_ms_bucket{le="250"}[30m]))
          / sum(rate(game_action_ack_latency_ms_count[30m]))
      - record: game_action_ack_latency_ms:sli_latency:ratio_rate1h
        expr: sum(rate(game_action_ack_latency_ms_bucket{le="250"}[1h]))
          / sum(rate(game_action_ack_latency_ms_count[1h]))
      - record: game_action_ack_latency_ms:sli_latency:ratio_rate6h
        expr: sum(rate(game_action_ack_latency_ms_bucket{le="250"}[6h]))
          / sum(rate(game_action_ack_latency_ms_count[6h]))
      - record: game_action_ack_latency_error_budget:burn_rate5m
        expr: (1 - game_action_ack_latency_ms:sli_latency:ratio_rate5m) / (1 - 0.99)
      - record: game_action_ack_latency_error_budget:burn_rate30m
        expr: (1 - game_action_ack_latency_ms:sli_latency:ratio_rate30m) / (1 - 0.99)
      - record: game_action_ack_latency_error_budget:burn_rate1h
        expr: (1 - game_action_ack_latency_ms:sli_latency:ratio_rate1h) / (1 - 0.99)
      - record: game_action_ack_latency_error_budget:burn_rate6h
        expr: (1 - game_action_ack_latency_ms:sli_latency:ratio_rate6h) / (1 - 0.99)
  - name: game-action-ack-latency-alerts
    rules:
      - alert: GameActionAckLatencySLOBurnRateFast
        expr: game_action_ack_latency_error_budget:burn_rate5m > 14.4 and game_action_ack_latency_error_budget:burn_rate1h > 14.4
        for: 2m
        labels:
          severity: critical
          pagerduty_service: pokerhub-ops
        annotations:
          summary: "Short-window game action ACK latency burn rate too high"
          runbook: https://github.com/Nera26/pokerhub/blob/main/docs/runbooks/action-ack-latency.md
      - alert: GameActionAckLatencySLOBurnRateSlow
        expr: game_action_ack_latency_error_budget:burn_rate30m > 6 and game_action_ack_latency_error_budget:burn_rate6h > 6
        for: 15m
        labels:
          severity: critical
          pagerduty_service: pokerhub-ops
        annotations:
          summary: "Long-window game action ACK latency burn rate too high"
          runbook: https://github.com/Nera26/pokerhub/blob/main/docs/runbooks/action-ack-latency.md
      - alert: GameActionAckLatencyP95High
        expr: game_action_ack_latency_ms:p95 > 120
        for: 5m
        labels:
          severity: warning
          pagerduty_service: pokerhub-ops
        annotations:
          summary: "Game action ACK latency p95 > 120ms"
          runbook: https://github.com/Nera26/pokerhub/blob/main/docs/runbooks/action-ack-latency.md
      - alert: GameActionAckLatencyP99High
        expr: game_action_ack_latency_ms:p99 > 200
        for: 5m
        labels:
          severity: critical
          pagerduty_service: pokerhub-ops
        annotations:
          summary: "Game action ACK latency p99 > 200ms"
          runbook: https://github.com/Nera26/pokerhub/blob/main/docs/runbooks/action-ack-latency.md
