# SLO: 99.95% service uptime
---
groups:
  - name: uptime-slo
    rules:
      - record: service_uptime_ratio_rate5m
        expr: sum(rate(up[5m])) / count(rate(up[5m]))
      - record: service_uptime_ratio_rate30m
        expr: sum(rate(up[30m])) / count(rate(up[30m]))
      - record: service_uptime_ratio_rate1h
        expr: sum(rate(up[1h])) / count(rate(up[1h]))
      - record: service_uptime_ratio_rate6h
        expr: sum(rate(up[6h])) / count(rate(up[6h]))
      - record: service_uptime_error_budget_burn_rate_5m
        expr: (1 - service_uptime_ratio_rate5m) / (1 - 0.9995)
      - record: service_uptime_error_budget_burn_rate_30m
        expr: (1 - service_uptime_ratio_rate30m) / (1 - 0.9995)
      - record: service_uptime_error_budget_burn_rate_1h
        expr: (1 - service_uptime_ratio_rate1h) / (1 - 0.9995)
      - record: service_uptime_error_budget_burn_rate_6h
        expr: (1 - service_uptime_ratio_rate6h) / (1 - 0.9995)
  - name: uptime-alerts
    rules:
      - alert: ServiceUptimeSLOBurnRateFast
        expr: service_uptime_error_budget_burn_rate_5m > 14.4 and service_uptime_error_budget_burn_rate_1h > 14.4
        for: 2m
        labels:
          severity: critical
          pagerduty_service: pokerhub-ops
        annotations:
          summary: "Short-window uptime burn rate too high"
      - alert: ServiceUptimeSLOBurnRateSlow
        expr: service_uptime_error_budget_burn_rate_30m > 6 and service_uptime_error_budget_burn_rate_6h > 6
        for: 15m
        labels:
          severity: critical
          pagerduty_service: pokerhub-ops
        annotations:
          summary: "Long-window uptime burn rate too high"
