# SLO: 99.95% service uptime
---
groups:
  - name: uptime-slo
    rules:
      - record: service_uptime_ratio_rate1h
        expr: sum(rate(up[1h])) / count(rate(up[1h]))
      - record: service_uptime_ratio_rate6h
        expr: sum(rate(up[6h])) / count(rate(up[6h]))
      - record: service_uptime_error_budget_burn_rate_1h
        expr: (1 - service_uptime_ratio_rate1h) / (1 - 0.9995)
      - record: service_uptime_error_budget_burn_rate_6h
        expr: (1 - service_uptime_ratio_rate6h) / (1 - 0.9995)
  - name: uptime-alerts
    rules:
      - alert: ServiceUptimeSLOBurnRate1h
        expr: service_uptime_error_budget_burn_rate_1h > 14.4
        for: 2m
        labels:
          severity: critical
          pagerduty_service: pokerhub-ops
        annotations:
          summary: "1h uptime burn rate too high"
      - alert: ServiceUptimeSLOBurnRate6h
        expr: service_uptime_error_budget_burn_rate_6h > 6
        for: 15m
        labels:
          severity: critical
          pagerduty_service: pokerhub-ops
        annotations:
          summary: "6h uptime burn rate too high"
