apiVersion: batch/v1
kind: CronJob
metadata:
  name: pg-drill
spec:
  schedule: "0 2 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: drill
              image: ghcr.io/pokerhub/infra-tools:latest
              command:
                - /bin/bash
                - -c
                - |
                  set -euo pipefail
                  if ! command -v gcloud >/dev/null 2>&1; then
                    apt-get update && apt-get install -y google-cloud-cli >/dev/null 2>&1
                  fi
                  gcloud auth activate-service-account --key-file /var/secrets/gcloud/key.json
                  /scripts/tests/drill-failover.sh
              env:
                - name: PG_INSTANCE_ID
                  value: primary-pg
                - name: PRIMARY_REGION
                  value: us-west-2
                - name: SECONDARY_REGION
                  value: us-east-1
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: dr-postgres
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: dr-postgres
                      key: password
                - name: PGDATABASE
                  value: postgres
                - name: WAL_ARCHIVE_BUCKET
                  value: pg-wal-archive
              volumeMounts:
                - name: gcloud-key
                  mountPath: /var/secrets/gcloud
                  readOnly: true
          volumes:
            - name: gcloud-key
              secret:
                secretName: gcloud-service-account
