_format_version: "3.0"
upstreams:
  - name: backend-upstream
    hash_on: cookie
    hash_on_cookie: table_affinity
    hash_on_cookie_path: /
    targets:
      - target: backend-us:3000
      - target: backend-eu:3000
services:
  - name: backend
    host: backend-upstream
    port: 3000
    protocol: http
    routes:
      - name: backend-http
        paths:
          - /
        protocols:
          - http
          - https
      - name: backend-ws
        paths:
          - /socket.io
        protocols:
          - http
          - https
          - ws
          - wss
    plugins:
      - name: jwt
      - name: rate-limiting
        config:
          minute: 60
          policy: local
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Authorization
            - Content-Type
          exposed_headers:
            - X-RateLimit-Limit
            - X-RateLimit-Remaining
          credentials: true
          max_age: 3600
