- pattern: main
  required_status_checks:
    - ci
    - "ci / dr-runbook"
    - "ci / dr-trends"
    - "ci / workflow-sla"
    - "ci / ops-sla"
    - soak-metrics
    - contracts
    - "deploy / preflight"
    - "deploy / deploy"
    - check-proof-archive
    - proof-archive
    - "ci / ops-artifacts-verify"
    - spectator-retention
    - "ci / spectator-privacy"
    - soak
    - dr-heartbeat
