- pattern: main
  required_status_checks:
    - ci
    - "ci / dr-runbook"
    - "ci / workflow-sla"
    - contracts
    - "deploy / deploy"
    - proof-archive
    - check-proof-archive
    - ops-artifacts-verify
    - "ci / ops-artifacts"
    - soak
    - soak-smoke
    - "ci / spectator-privacy"
    - spectator-retention
    - "ci / soak-metrics"
