- pattern: main
  required_status_checks:
    - ci
    - "ci / dr-runbook"
    - contracts
    - deploy
    - "deploy / proof-archive"
    - check-proof-archive
    - ops-artifacts-verify
    - "ci / ops-artifacts"
    - soak
    - spectator-privacy # require spectator privacy workflow
