version: '3.8'
services:
  backend:
    build: ./backend
    command: npm run start:dev
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=pokerhub
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pokerhub
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
volumes:
  db-data:
