groups:
  - name: observability-alerts
    rules:
      - alert: UptimeSLOViolation
        expr: (1 - avg_over_time(service_availability_ratio[30d])) > (1 - 0.9995)
        for: 5m
        labels:
          severity: critical
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "Uptime below 99.95% SLO"
      - alert: ActionAckLatencySLOViolation
        expr: histogram_quantile(0.95, sum(rate(socket_action_ack_latency_ms_bucket[5m])) by (le)) > 120
        for: 5m
        labels:
          severity: critical
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "Action ACK latency p95 over 120ms"
      - alert: HttpApiLatencySLOViolation
        expr: histogram_quantile(0.99, sum(rate(http_server_requests_duration_seconds_bucket[5m])) by (le)) > 0.2
        for: 5m
        labels:
          severity: critical
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "HTTP API latency p99 over 200ms"
      - alert: WebSocketLatencySLOViolation
        expr: histogram_quantile(0.95, sum(rate(socket_message_latency_ms_bucket[5m])) by (le)) > 100
        for: 5m
        labels:
          severity: critical
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "WebSocket message latency p95 over 100ms"
      - alert: ErrorBudgetBurnRateFast
        expr: ((1 - avg_over_time(service_availability_ratio[5m])) / (1 - 0.9995)) > 14
        for: 2m
        labels:
          severity: critical
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "Fast burn: error budget consumed >14x over 5m"
      - alert: ErrorBudgetBurnRateSlow
        expr: ((1 - avg_over_time(service_availability_ratio[1h])) / (1 - 0.9995)) > 7
        for: 15m
        labels:
          severity: warning
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "Slow burn: error budget consumed >7x over 1h"
