groups:
  - name: pokerhub-slo-burn
    rules:
      - alert: LatencySLOBurnRate1h
        expr: latency_error_budget_burn_rate_1h > 14.4
        for: 2m
        labels:
          severity: critical
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "1h latency error budget burn rate too high"
          runbook: docs/runbooks/action-ack-latency.md
      - alert: LatencySLOBurnRate6h
        expr: latency_error_budget_burn_rate_6h > 6
        for: 15m
        labels:
          severity: critical
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "6h latency error budget burn rate too high"
          runbook: docs/runbooks/action-ack-latency.md
      - alert: ErrorRateSLOBurnRate1h
        expr: request_error_budget_burn_rate_1h > 14.4
        for: 2m
        labels:
          severity: critical
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "1h error rate budget burn rate too high"
          runbook: docs/runbooks/error-rates.md
      - alert: ErrorRateSLOBurnRate6h
        expr: request_error_budget_burn_rate_6h > 6
        for: 15m
        labels:
          severity: critical
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "6h error rate budget burn rate too high"
          runbook: docs/runbooks/error-rates.md
