apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-success
spec:
  metrics:
    - name: success-rate
      interval: 1m
      successCondition: result[0] > 0.99
      failureLimit: 1
      provider:
        prometheus:
          address: http://prometheus.monitoring.svc.cluster.local
          query: {{ .Values.analysis.successRateQuery | quote }}
