groups:
  - name: pokerhub-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_server_requests_errors_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
      - alert: HighLatency
        expr: histogram_quantile(0.95, sum(rate(http_server_requests_duration_seconds_bucket[5m])) by (le)) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High request latency"
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[1m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
      - alert: DroppedFrames
        expr: rate(game_frames_dropped_total[5m]) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Dropped frames detected"
      - alert: LatencySLOBurnRate1h
        expr: latency_error_budget_burn_rate_1h > 14.4
        for: 2m
        labels:
          severity: critical
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "1h latency error budget burn rate too high"
      - alert: LatencySLOBurnRate6h
        expr: latency_error_budget_burn_rate_6h > 6
        for: 15m
        labels:
          severity: critical
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "6h latency error budget burn rate too high"
      - alert: ErrorRateSLOBurnRate1h
        expr: request_error_budget_burn_rate_1h > 14.4
        for: 2m
        labels:
          severity: critical
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "1h error rate budget burn rate too high"
      - alert: ErrorRateSLOBurnRate6h
        expr: request_error_budget_burn_rate_6h > 6
        for: 15m
        labels:
          severity: critical
          pagerduty_service: pokerhub-sre
        annotations:
          summary: "6h error rate budget burn rate too high"
