apiVersion: batch/v1
kind: CronJob
metadata:
  name: clickhouse-snapshot-replication
spec:
  schedule: {{ .Values.clickhouseReplication.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: clickhouse-replicate
              image: {{ .Values.clickhouseReplication.image }}
              env:
                - name: BACKUP_BUCKET
                  value: {{ .Values.clickhouseReplication.backupBucket | quote }}
                - name: SECONDARY_REGION
                  value: {{ .Values.clickhouseReplication.secondaryRegion | quote }}
              command:
                - /bin/sh
                - -c
                - >-
                  set -euo pipefail;
                  echo "Syncing ClickHouse backups from $BACKUP_BUCKET to $SECONDARY_REGION";
                  gsutil -m rsync -r gs://$BACKUP_BUCKET gs://$BACKUP_BUCKET-$SECONDARY_REGION;
