apiVersion: batch/v1
kind: CronJob
metadata:
  name: clickhouse-snapshot-replication
spec:
  schedule: {{ .Values.clickhouseReplication.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: clickhouse-replicate
              image: {{ .Values.clickhouseReplication.image }}
              env:
                - name: BACKUP_BUCKET
                  value: {{ .Values.clickhouseReplication.backupBucket | quote }}
                - name: SECONDARY_REGION
                  value: {{ .Values.clickhouseReplication.secondaryRegion | quote }}
              command:
                - /bin/sh
                - -c
                - >-
                  set -euo pipefail;
                  echo "Replicating ClickHouse backups from gs://$BACKUP_BUCKET to region $SECONDARY_REGION...";
                  SECONDARY_BUCKET="${BACKUP_BUCKET}-${SECONDARY_REGION}";
                  if gsutil ls -b "gs://${SECONDARY_BUCKET}" >/dev/null 2>&1; then
                    echo "Secondary bucket gs://${SECONDARY_BUCKET} exists.";
                  else
                    echo "Creating secondary bucket gs://${SECONDARY_BUCKET} in region ${SECONDARY_REGION}...";
                    gsutil mb -l "${SECONDARY_REGION}" -b on "gs://${SECONDARY_BUCKET}";
                  fi;
                  echo "Starting rsync...";
                  gsutil -m rsync -r "gs://${BACKUP_BUCKET}" "gs://${SECONDARY_BUCKET}";
                  echo "Rsync completed successfully.";
