apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-snapshot-replication
spec:
  schedule: {{ .Values.redisReplication.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: redis-replicate
              image: {{ .Values.redisReplication.image }}
              env:
                - name: REDIS_CLUSTER_ID
                  value: {{ .Values.redisReplication.clusterId | quote }}
                - name: SECONDARY_REGION
                  value: {{ .Values.redisReplication.secondaryRegion | quote }}
              command:
                - /bin/sh
                - -c
                - >-
                  echo "Replicating Redis snapshot for $REDIS_CLUSTER_ID to $SECONDARY_REGION";
                  # Placeholder for aws elasticache create-snapshot && copy-snapshot
