name: "Ops preflight"
description: "Run spectator-privacy, soak metric, DR SLA and proof-archive checks"
inputs:
  slack-channel-id:
    description: "Slack channel to notify on failure"
    required: true
  spectator-privacy-sla-hours:
    description: "Maximum age for spectator-privacy-nightly workflow"
    required: false
    default: 24
  soak-metrics-sla-hours:
    description: "Maximum age for soak-metrics workflow"
    required: true
  dr-drill-sla-days:
    description: "Max age for dr-drill workflow"
    required: true
  dr-failover-sla-days:
    description: "Max age for dr-failover workflow"
    required: true
  dr-restore-sla-days:
    description: "Max age for dr-restore workflow"
    required: true
  dr-throwaway-sla-days:
    description: "Max age for dr-throwaway workflow"
    required: true
  proof-archive-sla-hours:
    description: "Maximum age for proof-archive workflow"
    required: false
    default: 24
runs:
  using: "composite"
  steps:
    - name: Check spectator-privacy-nightly SLA
      uses: ./.github/workflows/check-workflow-sla
      with:
        workflow: spectator-privacy-nightly.yml
        sla: ${{ inputs.spectator-privacy-sla-hours }}
        unit: hours
        slack-channel-id: ${{ inputs.slack-channel-id }}
    - name: Check soak-metrics SLA
      uses: ./.github/workflows/check-workflow-sla
      with:
        workflow: soak-metrics.yml
        sla: ${{ inputs.soak-metrics-sla-hours }}
        unit: hours
        slack-channel-id: ${{ inputs.slack-channel-id }}
    - name: Check soak metrics thresholds
      run: |
        npx ts-node scripts/check-soak-metrics.ts
        if [ ! -f soak-summary.json ]; then
          echo "soak-summary.json missing" >&2
          exit 1
        fi
      env:
        SOAK_TRENDS_BUCKET: ${{ env.SOAK_TRENDS_BUCKET }}
        SOAK_LATENCY_P95_MS: ${{ env.SOAK_LATENCY_P95_MS }}
        SOAK_THROUGHPUT_MIN: ${{ env.SOAK_THROUGHPUT_MIN }}
    - name: Check DR drill SLA
      uses: ./.github/workflows/check-workflow-sla
      with:
        workflow: dr-drill.yml
        sla: ${{ inputs.dr-drill-sla-days }}
        unit: days
        slack-channel-id: ${{ inputs.slack-channel-id }}
    - name: Check DR failover SLA
      uses: ./.github/workflows/check-workflow-sla
      with:
        workflow: dr-failover.yml
        sla: ${{ inputs.dr-failover-sla-days }}
        unit: days
        slack-channel-id: ${{ inputs.slack-channel-id }}
    - name: Check DR restore SLA
      uses: ./.github/workflows/check-workflow-sla
      with:
        workflow: dr-restore.yml
        sla: ${{ inputs.dr-restore-sla-days }}
        unit: days
        slack-channel-id: ${{ inputs.slack-channel-id }}
    - name: Check DR throwaway SLA
      uses: ./.github/workflows/check-workflow-sla
      with:
        workflow: dr-throwaway.yml
        sla: ${{ inputs.dr-throwaway-sla-days }}
        unit: days
        slack-channel-id: ${{ inputs.slack-channel-id }}
    - name: Check DR trend targets
      run: |
        set -euo pipefail
        out=$(npx -y ts-node infra/disaster-recovery/check-dr-trends.ts)
        echo "$out"
        latest_rto=$(echo "$out" | jq -r '.latest.rto')
        avg_rto=$(echo "$out" | jq -r '.average.rto')
        latest_rpo_snap=$(echo "$out" | jq -r '.latest.rpoSnap')
        latest_rpo_wal=$(echo "$out" | jq -r '.latest.rpoWal')
        avg_rpo_snap=$(echo "$out" | jq -r '.average.rpoSnap')
        avg_rpo_wal=$(echo "$out" | jq -r '.average.rpoWal')
        if [ "$latest_rto" -gt "$RTO_TARGET" ] || [ "$avg_rto" -gt "$RTO_TARGET" ] \
          || [ "$latest_rpo_snap" -gt "$RPO_TARGET" ] || [ "$latest_rpo_wal" -gt "$RPO_TARGET" ] \
          || [ "$avg_rpo_snap" -gt "$RPO_TARGET" ] || [ "$avg_rpo_wal" -gt "$RPO_TARGET" ]; then
          echo 'DR metrics exceed targets'
          exit 1
        fi
      env:
        DR_METRICS_BUCKET: ${{ env.DR_METRICS_BUCKET }}
        RTO_TARGET: ${{ env.RTO_TARGET }}
        RPO_TARGET: ${{ env.RPO_TARGET }}
    - name: Check proof-archive SLA
      uses: ./.github/workflows/check-workflow-sla
      with:
        workflow: proof-archive.yml
        sla: ${{ inputs.proof-archive-sla-hours }}
        unit: hours
        slack-channel-id: ${{ inputs.slack-channel-id }}
