---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/pokerhub/api:latest
          env:
            - name: DB_PRIMARY_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-endpoints
                  key: PRIMARY_ENDPOINT
            - name: DATABASE_URL
              value: postgres://postgres:postgres@$(DB_PRIMARY_HOST):5432/pokerhub
            - name: DB_REPLICA_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-endpoints
                  key: REPLICA_ENDPOINT
            - name: DB_FAILOVER_STRATEGY
              value: promote-replica
            - name: ALERTMANAGER_URL
              value: http://alertmanager:9093
          resources:
            requests:
              cpu: "1"
            limits:
              cpu: "1"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 3000
