alertmanager:
  config: |
    global: {}
    route:
      receiver: 'null'
      routes:
        - match_re:
            pagerduty_service: .+
          receiver: pagerduty
    receivers:
      - name: pagerduty
        pagerduty_configs:
          - routing_key: ${pagerduty_routing_key}
serverFiles:
  alerts:
    slo-alerts.yaml: |
      groups:
      - name: uptime
        rules:
        - alert: ServiceUptimeSLO
          expr: (sum(rate(http_requests_total{status!~"5.."}[5m])) / sum(rate(http_requests_total[5m]))) < 0.999
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Service uptime below SLO"
            description: "Less than 99.9% of requests are succeeding."
      - name: ack-latency
        rules:
        - alert: AckLatencySLO
          expr: histogram_quantile(0.99, sum(rate(ack_latency_seconds_bucket[5m])) by (le)) > 0.25
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: "ACK latency above SLO"
            description: "99th percentile ACK latency > 250ms."
      - name: slo-burn-rate
        rules:
        - alert: LatencySLOBurnRate1h
          expr: latency_error_budget_burn_rate_1h > 14.4
          for: 2m
          labels:
            severity: critical
            pagerduty_service: pokerhub-sre
          annotations:
            summary: "1h latency error budget burn rate too high"
        - alert: LatencySLOBurnRate6h
          expr: latency_error_budget_burn_rate_6h > 6
          for: 15m
          labels:
            severity: critical
            pagerduty_service: pokerhub-sre
          annotations:
            summary: "6h latency error budget burn rate too high"
        - alert: ErrorRateSLOBurnRate1h
          expr: request_error_budget_burn_rate_1h > 14.4
          for: 2m
          labels:
            severity: critical
            pagerduty_service: pokerhub-sre
          annotations:
            summary: "1h error rate budget burn rate too high"
        - alert: ErrorRateSLOBurnRate6h
          expr: request_error_budget_burn_rate_6h > 6
          for: 15m
          labels:
            severity: critical
            pagerduty_service: pokerhub-sre
          annotations:
            summary: "6h error rate budget burn rate too high"
