openapi: 3.1.0
info:
  title: PokerHub API
  version: 1.0.0
paths:
  /status:
    get:
      summary: Get service status
      responses:
        '200':
          description: Service status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
  /wallet/{id}/withdraw:
    post:
      summary: Withdraw funds
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawRequest'
      responses:
        '200':
          description: Withdrawal result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
components:
  schemas:
    StatusResponse:
      type: object
      properties:
        status:
          type: string
      required:
        - status
    LoginResponse:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    MessageResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    WithdrawRequest:
      type: object
      properties:
        amount:
          type: number
        deviceId:
          type: string
      required:
        - amount
        - deviceId
