openapi: 3.1.0
info:
  title: PokerHub API
  version: 1.0.0
paths:
  /status:
    get:
      summary: Get service status
      responses:
        '200':
          description: Service status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
  /hands/{id}/proof:
    get:
      summary: Get hand proof
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Hand proof
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HandProof'
        '404':
          description: Proof not found
components:
  schemas:
    StatusResponse:
      type: object
      properties:
        status:
          type: string
      required:
        - status
    LoginResponse:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    MessageResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    HandProof:
      type: object
      properties:
        seed:
          type: string
        nonce:
          type: string
        commitment:
          type: string
      required:
        - seed
        - nonce
        - commitment
