openapi: 3.1.0
info:
  title: PokerHub API
  version: 1.0.0
paths:
  /status:
    get:
      summary: Get service status
      responses:
        '200':
          description: Service status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
  /leaderboard:
    get:
      summary: Get leaderboard
      responses:
        '200':
          description: Top players
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaderboardResponse'
  /leaderboard/rebuild:
    post:
      summary: Rebuild leaderboard
      parameters:
        - in: query
          name: days
          schema:
            type: integer
            minimum: 1
            default: 30
      responses:
        '200':
          description: Rebuild triggered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
components:
  schemas:
    StatusResponse:
      type: object
      properties:
        status:
          type: string
      required:
        - status
    LoginResponse:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    MessageResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    LeaderboardResponse:
      type: array
      items:
        type: string
