import * as Joi from 'joi';

export const validationSchema = Joi.object({
  DATABASE_URL: Joi.string().uri().required(),
  REDIS_URL: Joi.string().uri().required(),
  RABBITMQ_URL: Joi.string().uri().required(),
  GCP_PROJECT: Joi.string().required(),
  GCS_BUCKET: Joi.string().required(),
  GOOGLE_APPLICATION_CREDENTIALS: Joi.string().required(),
  GCS_EMULATOR_HOST: Joi.string().uri().optional(),
  CLICKHOUSE_URL: Joi.string().uri().optional(),
  KAFKA_BROKERS: Joi.string().optional(),
  ELASTIC_URL: Joi.string().uri().optional(),
  LOKI_URL: Joi.string().uri().optional(),
  OTEL_EXPORTER_OTLP_ENDPOINT: Joi.string().uri().optional(),
  OTEL_SERVICE_NAME: Joi.string().optional(),
  LOG_PROVIDER: Joi.string().optional(),
  PORT: Joi.number().integer().optional(),
  JWT_SECRET: Joi.string().required(),
  JWT_ACCESS_TTL: Joi.number().integer().optional(),
  JWT_REFRESH_TTL: Joi.number().integer().optional(),
  RATE_LIMIT_WINDOW: Joi.number().integer().optional(),
  RATE_LIMIT_MAX: Joi.number().integer().optional(),
  KYC_API_URL: Joi.string().uri().optional(),
  KYC_API_KEY: Joi.string().optional(),
  ALLOWED_COUNTRIES: Joi.string().optional(),
});
