import * as Joi from 'joi';

export const validationSchema = Joi.object({
  DATABASE_URL: Joi.string()
    .uri()
    .default('postgres://postgres:postgres@localhost:15432/pokerhub'),
  REDIS_URL: Joi.string().uri().optional().empty(''),
  REDIS_HOST: Joi.string().optional(),
  REDIS_PORT: Joi.number().integer().optional(),
  RABBITMQ_URL: Joi.string().uri().default('amqp://localhost:5672'),
  RABBITMQ_QUEUE: Joi.string().default('tournaments'),
  GCP_PROJECT: Joi.string().default('pokerhub-dev'),
  GCS_BUCKET: Joi.string().default('pokerhub-dev'),
  GOOGLE_APPLICATION_CREDENTIALS: Joi.string().allow('').default(''),
  GCS_EMULATOR_HOST: Joi.string().uri().optional().empty(''),
  CLICKHOUSE_URL: Joi.string().uri().optional().empty(''),
  KAFKA_BROKERS: Joi.string().optional(),
  ELASTIC_URL: Joi.string().uri().optional().empty(''),
  LOKI_URL: Joi.string().uri().optional().empty(''),
  OTEL_EXPORTER_OTLP_ENDPOINT: Joi.string().uri().optional().empty(''),
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: Joi.string().uri().optional().empty(''),
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: Joi.string().uri().optional().empty(''),
  OTEL_EXPORTER_PROMETHEUS_PORT: Joi.number().integer().optional(),
  OTEL_EXPORTER_PROMETHEUS_HOST: Joi.string().optional(),
  OTEL_EXPORTER_PROMETHEUS_ENDPOINT: Joi.string().optional().empty(''),
  OTEL_SERVICE_NAME: Joi.string().optional().empty(''),
  LOG_PROVIDER: Joi.string().optional().empty(''),
  BACKEND_PORT: Joi.number().integer().optional().empty(''),
  PORT: Joi.number().integer().optional().empty(''),
  JWT_SECRETS: Joi.string().default('dev-secret'),
  JWT_ACCESS_TTL: Joi.number().integer().optional().empty(''),
  JWT_REFRESH_TTL: Joi.number().integer().optional().empty(''),
  RATE_LIMIT_WINDOW: Joi.number().integer().optional().empty(''),
  RATE_LIMIT_MAX: Joi.number().integer().optional().empty(''),
  DB_SYNC: Joi.boolean().optional(),
  KYC_API_URL: Joi.string().uri().optional().empty(''),
  KYC_API_KEY: Joi.string().optional().empty(''),
  KYC_BLOCKED_COUNTRIES: Joi.string().optional().empty(''),
  KYC_BLOCKED_REGIONS: Joi.string().optional().empty(''),
  GEOIP_PROVIDER_URL: Joi.string().uri().optional().empty(''),
  SANCTIONS_PROVIDER_URL: Joi.string().uri().optional().empty(''),
  PEP_PROVIDER_URL: Joi.string().uri().optional().empty(''),
  ONFIDO_API_TOKEN: Joi.string().optional().empty(''),
  ALLOWED_COUNTRIES: Joi.string().optional().empty(''),
  STRIPE_API_KEY: Joi.string().optional().empty(''),
  PAYMENT_PROVIDER_BASE_URL: Joi.string()
    .uri()
    .default('https://api.stripe.com/v1'),
  DEFAULT_CURRENCY: Joi.string().length(3).default('usd'),
  PROVIDER_WEBHOOK_SECRET: Joi.string().optional().empty(''),
  WALLET_DAILY_DEPOSIT_LIMIT: Joi.number().integer().optional().empty(''),
  WALLET_DAILY_WITHDRAW_LIMIT: Joi.number().integer().optional().empty(''),
  WALLET_VELOCITY_DEPOSIT_HOURLY_COUNT: Joi.number().integer().optional().empty(''),
  WALLET_VELOCITY_DEPOSIT_HOURLY_AMOUNT: Joi.number().integer().optional().empty(''),
  WALLET_VELOCITY_DEPOSIT_DAILY_COUNT: Joi.number().integer().optional().empty(''),
  WALLET_VELOCITY_WITHDRAW_HOURLY_COUNT: Joi.number().integer().optional().empty(''),
  WALLET_VELOCITY_WITHDRAW_HOURLY_AMOUNT: Joi.number().integer().optional().empty(''),
  WALLET_VELOCITY_WITHDRAW_DAILY_COUNT: Joi.number().integer().optional().empty(''),
  WALLET_CHARGEBACK_WINDOW_DAYS: Joi.number().integer().optional().empty(''),
  WALLET_CHARGEBACK_ACCOUNT_LIMIT: Joi.number().integer().optional().empty(''),
  WALLET_CHARGEBACK_DEVICE_LIMIT: Joi.number().integer().optional().empty(''),
  LEADERBOARD_REBUILD_CRON: Joi.string().optional().empty(''),
  GATEWAY_QUEUE_LIMIT: Joi.number().integer().optional().empty(''),
  GATEWAY_GLOBAL_LIMIT: Joi.number().integer().optional().empty(''),
  SPECTATOR_QUEUE_LIMIT: Joi.number().integer().optional().empty(''),
  SPECTATOR_RATE_LIMIT: Joi.number().integer().optional().empty(''),
  SPECTATOR_INTERVAL_MS: Joi.number().integer().optional().empty(''),
  SOCKETS: Joi.number().integer().optional().empty(''),
  TABLES: Joi.number().integer().optional().empty(''),
  WS_URL: Joi.string().uri().optional().empty(''),
  PACKET_LOSS: Joi.number().optional().empty(''),
  JITTER_MS: Joi.number().integer().optional().empty(''),
  ACK_P95_MS: Joi.number().integer().optional().empty(''),
  ACTION_TIMEOUT_MS: Joi.number().integer().optional().empty(''),
  DURATION_SEC: Joi.number().integer().optional().empty(''),
  LATENCY_MS: Joi.number().integer().optional().empty(''),
  GC_P95_MS: Joi.number().integer().optional().empty(''),
  METRICS_PORT: Joi.number().integer().optional().empty(''),
  RAKE_CONFIG: Joi.string().optional().empty(''),
  TOURNAMENT_AVOID_WITHIN: Joi.number().integer().min(0).optional().empty(''),
  SYSTEM_ACCOUNTS: Joi.string().optional().empty(''),
});
