global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'k6'
    static_configs:
      - targets: ['host.docker.internal:5656']
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:9464']
