name: Archive analytics events
concurrency:
  group: "Archive analytics events"
  cancel-in-progress: true

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-proof-archive:
    if: ${{ always() }}
    uses: ./.github/workflows/check-proof-archive.yml
    secrets: inherit
  archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: npm ci --prefix scripts
    - run: npx ts-node scripts/archive-events.ts

    needs:
    - check-proof-archive
  spectator-privacy:
    if: ${{ always() }}
    uses: ./.github/workflows/spectator-privacy.yml
    secrets: inherit
    with:
      logs: backend-tests.log frontend-tests.log integration.log property.log
    needs:
    - check-proof-archive
