name: backup-verify
concurrency:
  group: "backup-verify"
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Verify backups
        run: bash infra/scripts/verify-backups.sh
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: ${{ vars.SECONDARY_REGION }}
          PG_BACKUP_ID: ${{ vars.PG_BACKUP_ID }}
          REDIS_BACKUP_ID: ${{ vars.REDIS_BACKUP_ID }}
      - name: Restore snapshots to test cluster
        run: bash infra/scripts/restore-test-cluster.sh
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: ${{ vars.SECONDARY_REGION }}
          PG_BACKUP_ID: ${{ vars.PG_BACKUP_ID }}
          REDIS_BACKUP_ID: ${{ vars.REDIS_BACKUP_ID }}
      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            { "text": "Backup verification failed for ${GITHUB_REPOSITORY}@${GITHUB_SHA}" }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
