name: backup-restore
concurrency:
  group: "backup-restore"
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  restore:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Run backup restore test
        run: bash infra/disaster-recovery/tests/restore-backup.sh | tee restore.log
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          PG_BACKUP_ID: ${{ vars.PG_BACKUP_ID }}
          SECONDARY_REGION: ${{ vars.SECONDARY_REGION }}
      - name: Publish metrics
        run: |
          source restore-backup.metrics
          cat <<METRICS | curl --data-binary @- ${{ vars.PUSHGATEWAY_URL }}/metrics/job/backup-restore
          dr_backup_restore_rto_seconds $RTO_SECONDS
          dr_backup_restore_rpo_seconds $RPO_SECONDS
          METRICS
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: backup-restore
          path: |
            restore.log
            restore-backup.metrics
      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            { "text": "Backup restore test failed for ${GITHUB_REPOSITORY}@${GITHUB_SHA}" }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
