name: bot simulation

on:
  push:
    paths:
    - 'load/simulate-bots.js'
    - 'docs/tournament-handbook.md'
    - '.github/workflows/bot-simulation.yml'
  pull_request:
    paths:
    - 'load/simulate-bots.js'
    - 'docs/tournament-handbook.md'
    - '.github/workflows/bot-simulation.yml'

jobs:
  check-proof-archive:
    if: ${{ always() }}
    uses: ./.github/workflows/check-proof-archive.yml
    secrets: inherit
  preflight:
    runs-on: ubuntu-latest
    env:
      DR_DRILL_SLA_DAYS: 7
      DR_FAILOVER_SLA_DAYS: 30
      DR_RESTORE_SLA_DAYS: 30
      DR_THROWAWAY_SLA_DAYS: 7
      SOAK_SLA_HOURS: 24
    steps:
    - uses: ./.github/actions/ops-preflight
      with:
        slack-channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        soak-metrics-sla-hours: ${{ env.SOAK_SLA_HOURS }}
        dr-drill-sla-days: ${{ env.DR_DRILL_SLA_DAYS }}
        dr-failover-sla-days: ${{ env.DR_FAILOVER_SLA_DAYS }}
        dr-restore-sla-days: ${{ env.DR_RESTORE_SLA_DAYS }}
        dr-throwaway-sla-days: ${{ env.DR_THROWAWAY_SLA_DAYS }}

    needs:
    - check-proof-archive
  simulate:
    needs:
    - preflight
    - check-proof-archive
    runs-on: ubuntu-latest
    env:
      PROOF_ARCHIVE_BUCKET: ${{ secrets.PROOF_ARCHIVE_BUCKET }}
      PROOF_ARCHIVE_EXPECTED_DAILY_COUNT: ${{ 
        vars.PROOF_ARCHIVE_EXPECTED_DAILY_COUNT }}
      PROOF_ARCHIVE_KMS_KEY: ${{ vars.PROOF_ARCHIVE_KMS_KEY }}
      PROOF_MANIFEST_KMS_KEY: ${{ vars.PROOF_MANIFEST_KMS_KEY }}
      PROOF_MANIFEST_KMS_KEYRING: ${{ vars.PROOF_MANIFEST_KMS_KEYRING }}
      PROOF_MANIFEST_KMS_LOCATION: ${{ vars.PROOF_MANIFEST_KMS_LOCATION }}
      PROOF_MANIFEST_KMS_VERSION: ${{ vars.PROOF_MANIFEST_KMS_VERSION || 1 }}
      SECONDARY_REGION: ${{ vars.SECONDARY_REGION }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID || vars.GCP_PROJECT_ID }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER
        || vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT || 
        vars.GCP_SERVICE_ACCOUNT }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Run bot simulation
      env:
        CLICKHOUSE_DSN: ${{ secrets.CLICKHOUSE_DSN }}
      run: |
        node load/simulate-bots.js --hands 1000 --players 9
    - uses: ./.github/actions/spectator-privacy-check
    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
    - run: npx ts-node scripts/check-proof-archive.ts
    - name: Verify sanitized logs
      run: |
        if rg -i "userId|tableSecret|sessionToken|email|ipAddress|authToken" backend-tests.log frontend-tests.log; then
          echo "PII found in logs" >&2
          exit 1
        fi
    - name: Upload sanitized logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bot-simulation-logs
        path: |
          backend-tests.log
          frontend-tests.log

  spectator-privacy:
    uses: ./.github/workflows/spectator-privacy.yml
    secrets: inherit
    with:
      logs: backend-tests.log frontend-tests.log integration.log property.log
    needs:
    - check-proof-archive
