name: bot simulation

on:
  push:
    paths:
      - 'load/simulate-bots.js'
      - 'docs/tournament-handbook.md'
      - '.github/workflows/bot-simulation.yml'
  pull_request:
    paths:
      - 'load/simulate-bots.js'
      - 'docs/tournament-handbook.md'
      - '.github/workflows/bot-simulation.yml'

jobs:
  preflight:
    runs-on: ubuntu-latest
    env:
      DR_DRILL_SLA_DAYS: 7
      DR_FAILOVER_SLA_DAYS: 30
      DR_RESTORE_SLA_DAYS: 30
      DR_THROWAWAY_SLA_DAYS: 7
      SOAK_SLA_HOURS: 24
    steps:
      - uses: ./.github/actions/ops-preflight
        with:
          slack-channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          soak-metrics-sla-hours: ${{ env.SOAK_SLA_HOURS }}
          dr-drill-sla-days: ${{ env.DR_DRILL_SLA_DAYS }}
          dr-failover-sla-days: ${{ env.DR_FAILOVER_SLA_DAYS }}
          dr-restore-sla-days: ${{ env.DR_RESTORE_SLA_DAYS }}
          dr-throwaway-sla-days: ${{ env.DR_THROWAWAY_SLA_DAYS }}

  simulate:
    needs: preflight
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run bot simulation
        env:
          CLICKHOUSE_DSN: ${{ secrets.CLICKHOUSE_DSN }}
        run: |
          node load/simulate-bots.js --hands 1000 --players 9
