name: canary-rollback

on:
  repository_dispatch:
    types: [canary-burn]

jobs:
  preflight:
    runs-on: ubuntu-latest
    env:
      DR_DRILL_SLA_DAYS: 7
      DR_FAILOVER_SLA_DAYS: 30
      DR_RESTORE_SLA_DAYS: 30
      DR_THROWAWAY_SLA_DAYS: 7
      SOAK_SLA_HOURS: 24
    steps:
      - uses: ./.github/actions/ops-preflight
        with:
          slack-channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          soak-metrics-sla-hours: ${{ env.SOAK_SLA_HOURS }}
          dr-drill-sla-days: ${{ env.DR_DRILL_SLA_DAYS }}
          dr-failover-sla-days: ${{ env.DR_FAILOVER_SLA_DAYS }}
          dr-restore-sla-days: ${{ env.DR_RESTORE_SLA_DAYS }}
          dr-throwaway-sla-days: ${{ env.DR_THROWAWAY_SLA_DAYS }}

  rollback:
    needs: preflight
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Configure kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.3
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0
      - name: Run rollback
        env:
          PROM_URL: ${{ vars.PROMETHEUS_URL }}
          NAMESPACE: ${{ vars.K8S_NAMESPACE }}
        run: |
          if ! bash infra/canary/rollback.sh; then
            helm rollback canary --namespace "$NAMESPACE"
          fi
