name: canary-deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/room-worker:${{ github.sha }} .
      - name: Push image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository }}/room-worker:${{ github.sha }}
      - name: Configure kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.3
      - name: Deploy canary
        run: |
          kubectl apply -f infra/tests/load/k8s-room-workers.yaml
          kubectl set image deployment/room-worker room-worker=ghcr.io/${{ github.repository }}/room-worker:${{ github.sha }} \
            --record
          kubectl rollout status deployment/room-worker --timeout=120s
      - name: Run k6 load test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: infra/tests/load/k6-room-workers.js
          arguments: --summary-export=summary.json
      - name: Rollback on failure
        if: failure()
        run: |
          kubectl rollout undo deployment/room-worker
      - name: Upload summary
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: k6-summary
          path: summary.json
