name: monthly-chaos-drill
concurrency:
  group: "monthly-chaos-drill"
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  chaos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run k6 latency chaos
        uses: grafana/k6-action@v0.2.0
        with:
          filename: load/chaos/k6-latency.js
          flags: --vus 50 --duration 1m --summary-export=k6-latency.json
      - name: Install Artillery
        run: npm install -g artillery@2
      - name: Run Artillery packet loss test
        run: artillery run load/chaos/artillery-packet-loss.yml --output artillery-packet-loss.json
      - name: Upload chaos artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: chaos-drill
          path: |
            k6-latency.json
            artillery-packet-loss.json

  soak-metrics:
    needs: chaos
    if: ${{ always() }}
    uses: ./.github/workflows/soak-metrics.yml
    secrets: inherit

  spectator-privacy:
    needs: [chaos, soak-metrics]
    if: ${{ always() }}
    uses: ./.github/workflows/spectator-privacy.yml
    secrets: inherit
    with:
      logs: backend-tests.log frontend-tests.log integration.log property.log
