name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run docs:lint

  unit:
    needs: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: ./scripts/test-stages.sh unit | tee unit.log
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-${{ github.sha }}
          path: unit.log

  property:
    # Property-based tests; see docs/test-strategy.md
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: ./scripts/test-stages.sh property | tee property.log
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: property-${{ github.sha }}
          path: property.log
  integration:
    needs: property
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: ./scripts/test-stages.sh integration | tee integration.log
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-${{ github.sha }}
          path: integration.log

  e2e:
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: ./scripts/test-stages.sh e2e | tee e2e.log
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-${{ github.sha }}
          path: e2e.log

  load:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: grafana/setup-k6@v1
      - run: ./scripts/test-stages.sh load | tee load.log
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: load-${{ github.sha }}
          path: load.log

  chaos:
    needs: load
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: grafana/setup-k6@v1
      - run: ./scripts/test-stages.sh chaos | tee chaos.log
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: chaos-${{ github.sha }}
          path: chaos.log
