name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm ci --prefix backend
      - run: npm ci --prefix frontend
      - run: npm run lint --prefix backend
      - run: npm test --prefix backend
      - run: npm run lint --prefix frontend
      - run: npm test --prefix frontend
      - run: npm run test:contracts
      - run: ./contracts/verify-contract.sh
      - run: ./scripts/check-contract-drift.sh

  property:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm install --no-save fast-check
      - run: npm test --prefix backend -- test/game/.*\.property\.spec\.ts
        env:
          FC_SEED: 1
      - run: node -r ts-node/register shared/test/verify.property.ts
        env:
          FC_SEED: 1

  integration:
    needs: property
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run test:e2e --prefix backend
      - run: npm run test:e2e:integration --prefix frontend

  e2e:
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run test:e2e

  load:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Run k6 smoke test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: load/k6-ws-packet-loss.js
          arguments: --vus 10 --duration 10s

  chaos:
    needs: load
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Run chaos test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: load/chaos/ws-chaos.js
          arguments: --vus 10 --duration 10s
