name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  workflow-sla:
    runs-on: ubuntu-latest
    steps:
      - name: Verify recent DR drill
        env:
          SLA_DAYS: 7
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          resp=$(curl -fsS -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/dr-drill.yml/runs?per_page=1")
          ts=$(echo "$resp" | jq -r '.workflow_runs[0].updated_at')
          conclusion=$(echo "$resp" | jq -r '.workflow_runs[0].conclusion')
          now=$(date -u +%s)
          run_ts=$(date -d "$ts" -u +%s)
          max_age=$((SLA_DAYS * 86400))
          age=$((now - run_ts))
          if [ "$conclusion" != "success" ]; then
            echo "Latest dr-drill run concluded with $conclusion" >&2
            exit 1
          fi
          if [ "$age" -gt "$max_age" ]; then
            echo "Latest dr-drill run is older than ${SLA_DAYS}d" >&2
            exit 1
          fi

      - name: Verify recent failover drill
        env:
          SLA_DAYS: 7
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          resp=$(curl -fsS -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/failover-drill.yml/runs?per_page=1")
          ts=$(echo "$resp" | jq -r '.workflow_runs[0].updated_at')
          conclusion=$(echo "$resp" | jq -r '.workflow_runs[0].conclusion')
          now=$(date -u +%s)
          run_ts=$(date -d "$ts" -u +%s)
          max_age=$((SLA_DAYS * 86400))
          age=$((now - run_ts))
          if [ "$conclusion" != "success" ]; then
            echo "Latest failover-drill run concluded with $conclusion" >&2
            exit 1
          fi
          if [ "$age" -gt "$max_age" ]; then
            echo "Latest failover-drill run is older than ${SLA_DAYS}d" >&2
            exit 1
          fi

      - name: Ensure proof-archive recent success
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          run=$(curl -fsS -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/proof-archive.yml/runs?per_page=1")
          conclusion=$(echo "$run" | jq -r '.workflow_runs[0].conclusion')
          started=$(echo "$run" | jq -r '.workflow_runs[0].run_started_at')
          start_ts=$(date -d "$started" +%s)
          now=$(date -u +%s)
          if [ "$conclusion" != "success" ] || [ $((now - start_ts)) -gt 86400 ]; then
            echo "Latest proof-archive workflow run did not succeed within 24 hours" >&2
            exit 1
          fi

      - uses: actions/checkout@v4
      - name: Verify proof archive integrity
        env:
          PROOF_ARCHIVE_BUCKET: ${{ secrets.PROOF_ARCHIVE_BUCKET }}
        run: npx -y ts-node scripts/check-proof-archive.ts

      - name: Ensure soak test recent success
        env:
          SLA_HOURS: 24
          GITHUB_TOKEN: ${{ github.token }}
          SOAK_TRENDS_BUCKET: ${{ secrets.SOAK_TRENDS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          set -euo pipefail
          run=$(curl -fsS -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/soak.yml/runs?per_page=1")
          conclusion=$(echo "$run" | jq -r '.workflow_runs[0].conclusion')
          started=$(echo "$run" | jq -r '.workflow_runs[0].run_started_at')
          start_ts=$(date -d "$started" +%s)
          now=$(date -u +%s)
          max_age=$((SLA_HOURS * 3600))
          if [ "$conclusion" != "success" ] || [ $((now - start_ts)) -gt "$max_age" ]; then
            echo "Latest soak workflow run did not succeed within ${SLA_HOURS} hours" >&2
            exit 1
          fi
          npx ts-node --compiler-options '{"module":"commonjs"}' scripts/check-soak-metrics.ts

      - name: Ensure spectator-privacy nightly recent success
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          run=$(curl -fsS -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/spectator-privacy-nightly.yml/runs?per_page=1")
          conclusion=$(echo "$run" | jq -r '.workflow_runs[0].conclusion')
          started=$(echo "$run" | jq -r '.workflow_runs[0].run_started_at')
          start_ts=$(date -d "$started" +%s)
          now=$(date -u +%s)
          if [ "$conclusion" != "success" ] || [ $((now - start_ts)) -gt 86400 ]; then
            echo "Latest spectator-privacy-nightly workflow run did not succeed within 24 hours" >&2
            exit 1
          fi

  docs:
    needs: workflow-sla
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run docs:lint
      - run: npm run docs:check

  dr-runbook-check:
    needs: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx ts-node scripts/check-dr-runbook.ts

  contracts:
    needs: [docs, dr-runbook-check]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm ci --prefix backend
      - run: npm ci --prefix frontend
      - name: Backend contract tests
        run: npm run test:contracts --prefix backend
      - name: Frontend contract tests
        run: npm run test:contracts --prefix frontend

  proof-archive:
    needs: contracts
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: proof
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/proof
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm ci --legacy-peer-deps --prefix backend
      - name: Seed proof fixture
        run: psql "$DATABASE_URL" -f backend/test/fixtures/proof-hand.sql
      - name: Export proof
        run: npx -y ts-node scripts/export-hand-proof.ts 11111111-1111-1111-1111-111111111111
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
      - name: Validate proof archive
        run: npx -y ts-node scripts/validate-proof-archive.ts

  proof-archive-integration:
    needs: proof-archive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm ci --legacy-peer-deps --prefix backend
      - name: Test proof archive migrations
        run: npx -y ts-node scripts/test-proof-archive-migrations.ts

  unit:
    needs:
      - contracts
      - proof-archive-integration
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: ./scripts/test-stages.sh unit | tee unit.log
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-${{ github.sha }}
          path: unit.log

  property:
    needs: unit
    if: ${{ always() }}
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: ./scripts/test-stages.sh property | tee property.log
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: property-${{ github.sha }}
          path: property.log
  spectator-privacy:
    needs: property
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/spectator-privacy-check
  integration:
    needs: spectator-privacy
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: ./scripts/test-stages.sh integration | tee integration.log
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-${{ github.sha }}
          path: integration.log

  e2e:
    needs: integration
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: ./scripts/test-stages.sh e2e | tee e2e.log
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-${{ github.sha }}
          path: e2e.log

  load:
    needs: e2e
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: grafana/setup-k6@v1
      - run: |
          mkdir -p load/results
          k6 run load/k6-swarm.js --vus 10 --duration 10s --summary-export=load/results/summary.json | tee load/results/k6.log
      - run: load/check-thresholds.sh load/results/summary.json
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: load-${{ github.sha }}
          path: |
            load/results/summary.json
            load/results/k6.log

  chaos:
    needs: load
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: grafana/setup-k6@v1
      - run: ./scripts/test-stages.sh chaos | tee chaos.log
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: chaos-${{ github.sha }}
          path: chaos.log

  soak:
    needs: chaos
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: grafana/setup-k6@v1
      - run: |
          mkdir -p load/results
          k6 run load/k6-ws-soak.js --vus 10 --duration 30s --summary-export=load/results/ws-soak-summary.json
      - run: load/check-thresholds.sh load/results/ws-soak-summary.json metrics/gc-histogram.json metrics/heap-histogram.json metrics/cpu-histogram.json
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Download latest baseline
        run: aws s3 sync "s3://${{ secrets.SOAK_TRENDS_BUCKET }}/soak/latest/" baseline || true
      - name: Threshold check against baseline
        id: threshold
        run: |
          if [ -f baseline/baseline.json ]; then
            npx ts-node --compiler-options '{"module":"commonjs"}' scripts/analyze-soak-trends.ts metrics baseline
          else
            echo "No baseline to compare against"
          fi
      - name: Open soak regression issue
        if: failure() && steps.threshold.outcome == 'failure'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Soak trends regression detected
          content-filepath: metrics/baseline.json
      - name: Prepare soak regression Slack payload
        if: failure() && steps.threshold.outcome == 'failure'
        run: jq -Rs '{channel: env.SLACK_CHANNEL_ID, text: .}' metrics/baseline.json > slack-payload.json
        env:
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      - name: Slack soak regression alert
        if: failure() && steps.threshold.outcome == 'failure'
        uses: slackapi/slack-github-action@v1
        with:
          method: chat.postMessage
          payload-file-path: slack-payload.json
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Sync soak metrics
        if: always()
        run: |
          aws s3 sync metrics "s3://${{ secrets.SOAK_TRENDS_BUCKET }}/soak-${{ github.run_id }}/"
          aws s3 sync metrics "s3://${{ secrets.SOAK_TRENDS_BUCKET }}/soak/latest/"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: soak-${{ github.sha }}
          path: |
            load/results/ws-soak-summary.json
            metrics/gc-histogram.json
            metrics/heap-histogram.json
            metrics/cpu-histogram.json
            metrics/baseline.json
