name: deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      DEPLOY_ENV: production
      K8S_NAMESPACE: ${{ vars.K8S_NAMESPACE }}
      HEALTH_CHECK_URL: ${{ vars.HEALTH_CHECK_URL }}
      METRICS_URL: ${{ vars.METRICS_URL }}
      ERROR_RATE_THRESHOLD: ${{ vars.ERROR_RATE_THRESHOLD }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Configure kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.3
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0
      - name: Validate observability configs
        run: |
          python -m pip install pyyaml >/dev/null
          python infra/observability/validate.py
      - name: Run canary deploy
        run: scripts/canary-deploy.sh
      - name: Check canary health
        id: check
        run: scripts/check-canary.sh
        continue-on-error: true
      - name: Rollback on health failure
        if: steps.check.outcome != 'success'
        run: |
          scripts/rollback.sh
          exit 1
      - name: Record canary metrics
        run: |
          mkdir -p load/metrics
          curl -fsS "$METRICS_URL" -o load/metrics/canary.json
      - name: Check real-time metrics
        id: metrics
        run: scripts/check-metrics.sh
        continue-on-error: true
      - name: Rollback on metrics failure
        if: steps.metrics.outcome != 'success'
        run: |
          scripts/rollback.sh
          exit 1
      - name: Run load tests
        id: load
        run: |
          npm install --no-save k6 >/dev/null
          for f in load/k6-*.js; do
            npx k6 run "$f" --vus 10 --duration 10s
          done
        continue-on-error: true
      - name: Rollback on load test failure
        if: steps.load.outcome != 'success'
        run: |
          scripts/rollback.sh
          exit 1
      - name: Promote canary
        if: steps.metrics.outcome == 'success' && steps.load.outcome == 'success'
        run: scripts/promote.sh
