name: dr-drill

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  drill:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Run disaster recovery drill
        run: bash infra/disaster-recovery/drill.sh
        env:
          PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          PG_INSTANCE_ID: ${{ vars.PG_INSTANCE_ID }}
          SECONDARY_REGION: ${{ vars.SECONDARY_REGION }}
          PGUSER: ${{ vars.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: postgres
          WAL_ARCHIVE_BUCKET: ${{ vars.WAL_ARCHIVE_BUCKET }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run restore health check
        run: npx -y ts-node infra/disaster-recovery/tests/restore.test.ts
        env:
          PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          PG_SNAPSHOT_ID: ${{ vars.PG_SNAPSHOT_ID }}
          PG_BACKUP_ID: ${{ vars.PG_SNAPSHOT_ID }}
          SECONDARY_REGION: ${{ vars.SECONDARY_REGION }}

      - name: Parse metrics
        id: metrics
        run: |
          source drill.metrics
          echo "rto=$RTO_SECONDS" >> "$GITHUB_OUTPUT"
          echo "rpo_snap=$RPO_SNAPSHOT_SECONDS" >> "$GITHUB_OUTPUT"
          echo "rpo_wal=$RPO_WAL_SECONDS" >> "$GITHUB_OUTPUT"

      - name: Check RTO/RPO objectives
        env:
          RTO: ${{ steps.metrics.outputs.rto }}
          RPO_SNAP: ${{ steps.metrics.outputs.rpo_snap }}
          RPO_WAL: ${{ steps.metrics.outputs.rpo_wal }}
          RTO_TARGET: 1800
          RPO_TARGET: 300
        run: |
          {
            echo "### DR Drill Metrics"
            echo "- RTO: ${RTO}s (target ≤ ${RTO_TARGET}s)"
            echo "- RPO (snapshot): ${RPO_SNAP}s (target ≤ ${RPO_TARGET}s)"
            echo "- RPO (WAL): ${RPO_WAL}s (target ≤ ${RPO_TARGET}s)"
          } >> "$GITHUB_STEP_SUMMARY"
          if [ "$RTO" -gt "$RTO_TARGET" ] || [ "$RPO_SNAP" -gt "$RPO_TARGET" ] || [ "$RPO_WAL" -gt "$RPO_TARGET" ]; then
            echo "RTO/RPO objectives exceeded" >&2
            exit 1
          fi

      - name: Upload metrics to GCS
        id: upload_metrics
        if: success()
        env:
          BUCKET: ${{ vars.DR_METRICS_BUCKET }}
        run: |
          uri="gs://$BUCKET/${GITHUB_RUN_ID}/drill.metrics"
          gcloud storage cp drill.metrics "$uri"
          url="https://storage.googleapis.com/$BUCKET/${GITHUB_RUN_ID}/drill.metrics"
          echo "url=$url" >> "$GITHUB_OUTPUT"

      - name: Publish drill results
        if: success()
        env:
          RTO: ${{ steps.metrics.outputs.rto }}
          RPO_SNAP: ${{ steps.metrics.outputs.rpo_snap }}
          RPO_WAL: ${{ steps.metrics.outputs.rpo_wal }}
          METRICS_URL: ${{ steps.upload_metrics.outputs.url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ts=$(date --iso-8601=seconds)
          perl -0 -i -pe "s/<!-- DR_DRILL_RESULTS -->/<!-- DR_DRILL_RESULTS -->\n- $ts: [metrics]($METRICS_URL) – RTO ${RTO}s, snapshot RPO ${RPO_SNAP}s, WAL RPO ${RPO_WAL}s/" docs/runbooks/disaster-recovery.md
          git config user.name github-actions
          git config user.email actions@github.com
          git commit -am "chore(dr): record drill results" && git push

      - name: Upload metrics
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dr-drill
          path: drill.metrics

      - name: PagerDuty alert on failure
        if: failure()
        env:
          ROUTING_KEY: ${{ secrets.PAGERDUTY_ROUTING_KEY }}
        run: |
          curl -X POST https://events.pagerduty.com/v2/enqueue \
            -H 'Content-Type: application/json' \
            -d '{"routing_key":"'$ROUTING_KEY'","event_action":"trigger","payload":{"summary":"DR drill failed","source":"github-actions","severity":"error"}}'

      - name: Create GitHub issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: DR drill failure
          content-filepath: drill.metrics
