name: dr-restore

on:
  workflow_dispatch:

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Fetch latest backup
        id: snap
        run: |
          SNAP_ID=$(gcloud sql backups list \
            --instance ${{ vars.DB_PRIMARY_ID }} \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --sort-by ~endTime \
            --limit 1 \
            --format 'value(id)')
          echo "snapshot_id=$SNAP_ID" >> "$GITHUB_OUTPUT"
      - name: Restore backup
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          PG_BACKUP_ID: ${{ steps.snap.outputs.snapshot_id }}
          SECONDARY_REGION: ${{ vars.SECONDARY_REGION }}
        run: |
          start=$(date +%s)
          bash infra/disaster-recovery/tests/restore-backup.sh
          end=$(date +%s)
          duration=$((end-start))
          echo "dr_restore_duration_seconds $duration" | \
            curl --data-binary @- ${{ vars.PUSHGATEWAY_URL }}/metrics/job/dr-restore
