name: dr-schedule
concurrency:
  group: "dr-schedule"
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  check-proof-archive:
    uses: ./.github/workflows/check-proof-archive.yml
    secrets: inherit

  dr-drill:
    needs: check-proof-archive
    uses: ./.github/workflows/dr-drill.yml
    secrets: inherit

  verify-drill:
    needs: dr-drill
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
      - name: Check DR runbook
        run: npx ts-node scripts/check-dr-runbook.ts
      - name: Check DR drill metrics
        env:
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          DR_DRILL_SLA_DAYS: 7
        run: npx ts-node scripts/check-dr-drill.ts

  dr-failover:
    needs: verify-drill
    uses: ./.github/workflows/dr-failover.yml
    secrets: inherit
