name: failover-drill

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  failover:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
      - name: Run failover drill
        run: bash infra/disaster-recovery/tests/failover.sh | tee failover.log
        env:
          PG_SNAPSHOT_ID: ${{ vars.PG_SNAPSHOT_ID }}
          CLICKHOUSE_SNAPSHOT: ${{ vars.CLICKHOUSE_SNAPSHOT }}
          SECONDARY_REGION: ${{ vars.SECONDARY_REGION }}
      - name: Check RTO/RPO
        run: |
          source failover.metrics
          echo "Start: $START_TIME"
          echo "End: $END_TIME"
          echo "RTO: $RTO_SECONDS seconds"
          echo "RPO: $RPO_SECONDS seconds"
          if [ "$RTO_SECONDS" -gt 1800 ]; then
            echo "RTO exceeds 30 minutes" >&2
            exit 1
          fi
          if [ "$RPO_SECONDS" -gt 300 ]; then
            echo "RPO exceeds 5 minutes" >&2
            exit 1
          fi
      - name: Upload metrics to GCS
        id: upload_metrics
        if: success()
        env:
          BUCKET: ${{ vars.DR_METRICS_BUCKET }}
        run: |
          uri="gs://$BUCKET/${GITHUB_RUN_ID}/dr-failover.metrics"
          gcloud storage cp failover.metrics "$uri"
          url="https://storage.googleapis.com/$BUCKET/${GITHUB_RUN_ID}/dr-failover.metrics"
          echo "url=$url" >> "$GITHUB_OUTPUT"
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: failover-log
          path: |
            failover.log
            failover.metrics
      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            { "text": "Failover drill failed for ${GITHUB_REPOSITORY}@${GITHUB_SHA}" }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
