name: failover-drill

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  failover:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Run failover drill
        run: bash infra/disaster-recovery/tests/failover.sh | tee failover.log
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PG_SNAPSHOT_ID: ${{ vars.PG_SNAPSHOT_ID }}
          CLICKHOUSE_SNAPSHOT: ${{ vars.CLICKHOUSE_SNAPSHOT }}
          SECONDARY_REGION: ${{ vars.SECONDARY_REGION }}
      - name: Check RTO/RPO
        run: |
          source failover.metrics
          echo "Start: $START_TIME"
          echo "End: $END_TIME"
          echo "RTO: $RTO_SECONDS seconds"
          echo "RPO: $RPO_SECONDS seconds"
          if [ "$RTO_SECONDS" -gt 1800 ]; then
            echo "RTO exceeds 30 minutes" >&2
            exit 1
          fi
          if [ "$RPO_SECONDS" -gt 300 ]; then
            echo "RPO exceeds 5 minutes" >&2
            exit 1
          fi
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: failover-log
          path: |
            failover.log
            failover.metrics
      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            { "text": "Failover drill failed for ${GITHUB_REPOSITORY}@${GITHUB_SHA}" }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
