name: failover-drill

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  failover:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Run failover drill
        run: bash infra/disaster-recovery/tests/failover.sh | tee failover.log
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PG_SNAPSHOT_ID: ${{ vars.PG_SNAPSHOT_ID }}
          CLICKHOUSE_SNAPSHOT: ${{ vars.CLICKHOUSE_SNAPSHOT }}
          SECONDARY_REGION: ${{ vars.SECONDARY_REGION }}
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: failover-log
          path: failover.log
      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            { "text": "Failover drill failed for ${GITHUB_REPOSITORY}@${GITHUB_SHA}" }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
