name: integration-tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  property-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend deps
        working-directory: backend
        run: npm ci
      - name: Run backend property tests
        working-directory: backend
        run: npm run test:property
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci
      - name: Run frontend property tests
        working-directory: frontend
        run: npm run test:property

  contract-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Generate OpenAPI diff
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff origin/${{ github.base_ref }} -- contracts/openapi.yaml > openapi.diff
      - name: Upload OpenAPI diff
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: openapi-diff
          path: openapi.diff
      - name: Verify shared types
        run: |
          npx -y openapi-zod-client contracts/openapi.yaml -o shared/types.ts --export-schemas
          git diff --exit-code shared/types.ts

  e2e:
    needs: [property-tests, contract-check]
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      - name: Install backend deps
        working-directory: backend
        run: npm ci
      - name: Run backend tests
        working-directory: backend
        run: npm test
      - name: Run leaderboard benchmark
        working-directory: backend
        run: npm run rebuild:leaderboard -- --benchmark --days=30 --players=5 --sessions=10 --assert-duration=1800000
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci
      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps
      - name: Start services
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml up -d --build
      - name: Run WebSocket load
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml run --rm load
      - name: Report ACK latency stats
        run: |
          node -e "const s=require('./load/ack-summary.json'); const m=s.metrics; console.log('p95', m.ack_latency.values['p(95)']); console.log('p99', m.ack_latency.values['p(99)']); console.log('ack_success_rate', m.ack_success.values.rate);"
      - name: Start toxiproxy
        run: docker run -d --name toxiproxy -p 8474:8474 -p 3001:3001 ghcr.io/shopify/toxiproxy
      - name: Run Socket.IO chaos load
        env:
          WS_URL: ws://localhost:3001
          TABLES: 10000
          SOCKETS: 80000
          UPSTREAM: localhost:4000
        run: npm run test:load
      - name: Upload Socket.IO latency histogram
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: socket-io-latency
          path: backend/latency-hist.json
      - name: Run integration tests (lobby + gameplay)
        working-directory: frontend
        run: npm run test:e2e:integration
      - name: Stop services
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml down -v
