name: k6-10k-chaos

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  chaos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install k6 and Artillery
        run: npm install -g k6 artillery
      - name: Run 10k chaos load
        run: ./load/run-10k-chaos.sh
        env:
          SOCKETS: 80000
          TABLES: 10000
          RNG_SEED: ${{ github.run_id }}
      - name: Check thresholds
        run: ./load/check-thresholds.sh load/metrics/k6-summary.json | tee -a "$GITHUB_STEP_SUMMARY"
      - name: Upload metrics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-10k-chaos
          path: load/metrics
