name: k6-swarm-ws

on:
  push:
    paths:
      - 'load/k6-swarm.js'
      - 'load/k6-ws-packet-loss.js'
      - '.github/workflows/k6-swarm-ws.yml'
  pull_request:
    paths:
      - 'load/k6-swarm.js'
      - 'load/k6-ws-packet-loss.js'
      - '.github/workflows/k6-swarm-ws.yml'

jobs:
  swarm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Socket.IO swarm against staging
        uses: grafana/k6-action@v0.2.0
        env:
          SIO_URL: ws://staging.pokerhub/game
          TABLES: 100
          SOCKETS: 100
          ACK_P95_MS: 120
          ACK_SUCCESS_RATE: 0.99
        with:
          filename: load/k6-swarm.js
          flags: --summary-export=swarm-summary.json --summary-trend-stats="avg,med,min,max,p(95),p(99)" --out json=swarm-metrics.json
      - name: Upload swarm metrics
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: k6-swarm
          path: |
            swarm-summary.json
            swarm-metrics.json

  ws-packet-loss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run WS packet loss against staging
        uses: grafana/k6-action@v0.2.0
        env:
          WS_URL: ws://staging.pokerhub
          PACKET_LOSS: 0.05
          VUS: 100
          DURATION: 1m
        with:
          filename: load/k6-ws-packet-loss.js
          flags: --summary-export=ws-summary.json --summary-trend-stats="avg,med,min,max,p(95),p(99)" --out json=ws-metrics.json
      - name: Upload ws metrics
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ws-packet-loss
          path: |
            ws-summary.json
            ws-metrics.json
