name: Leaderboard Rebuild

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci --prefix backend
      - run: npm run rebuild:leaderboard --prefix backend
