name: load-tests

on:
  workflow_dispatch:

jobs:
  k6-toxiproxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start staging stack
        run: |
          docker compose -f docker-compose.test.yml up -d redis backend
          sleep 10

      - name: Start toxiproxy
        run: |
          docker run -d --name toxiproxy -p 8474:8474 -p 3001:3001 ghcr.io/shopify/toxiproxy
          UPSTREAM=backend:3000 PACKET_LOSS=0.05 LATENCY_MS=200 ./load/toxiproxy.sh

      - name: Run k6 scenario
        uses: grafana/k6-action@v0.2.0
        env:
          WS_URL: ws://localhost:3001
          TABLES: 100
          SOCKETS: 100
          DURATION: 1m
          ACK_P95_MS: 120
          ACK_P99_MS: 200
        with:
          filename: load/k6-game-actions.js
          flags: --summary-export=load/k6-summary.json --out json=load/k6-metrics.json

      - name: Check thresholds
        run: ./load/check-thresholds.sh load/k6-summary.json

      - name: Capture backend stats
        if: always()
        run: docker stats backend --no-stream > backend-stats.txt

      - name: Collect logs
        if: always()
        run: docker logs toxiproxy > toxiproxy.log || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: load-test-results
          path: |
            load/k6-summary.json
            load/k6-metrics.json
            load/grafana-ack-latency.json
            load/grafana-stake-metrics.json
            backend-stats.txt
            toxiproxy.log
