name: load-test

on:
  workflow_dispatch:
  push:
    paths:
      - 'load/k6-10k-tables.js'
      - '.github/workflows/load-test.yml'
  pull_request:
    paths:
      - 'load/k6-10k-tables.js'
      - '.github/workflows/load-test.yml'

jobs:
  k6-load:
    runs-on: ubuntu-latest
    env:
      WS_URL: ${{ secrets.STAGING_WS_URL }}
      ACK_P50_MS: ${{ vars.ACK_P50_MS || '60' }}
      ACK_P95_MS: ${{ vars.ACK_P95_MS || '120' }}
      ACK_P99_MS: ${{ vars.ACK_P99_MS || '200' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install k6 and Artillery
        run: npm install -g k6 artillery

      - name: Run k6 10k tables scenario
        run: |
          k6 run load/k6-10k-tables.js \
            --summary-export=summary.json \
            --summary-trend-stats="avg,med,p(95),p(99)" \
            --out json=metrics.json

      - name: Check latency SLOs
        run: |
          p50=$(jq '.metrics.ack_latency["p(50)"] // .metrics.ack_latency.med' summary.json)
          p95=$(jq '.metrics.ack_latency["p(95)"]' summary.json)
          p99=$(jq '.metrics.ack_latency["p(99)"]' summary.json)
          echo "p50: $p50 ms"
          echo "p95: $p95 ms"
          echo "p99: $p99 ms"
          fail=0
          if (( $(echo "$p50 > $ACK_P50_MS" | bc -l) )); then
            echo "p50 latency $p50 ms exceeds $ACK_P50_MS ms"; fail=1
          fi
          if (( $(echo "$p95 > $ACK_P95_MS" | bc -l) )); then
            echo "p95 latency $p95 ms exceeds $ACK_P95_MS ms"; fail=1
          fi
          if (( $(echo "$p99 > $ACK_P99_MS" | bc -l) )); then
            echo "p99 latency $p99 ms exceeds $ACK_P99_MS ms"; fail=1
          fi
          exit $fail

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: k6-load-test
          path: |
            summary.json
            metrics.json
