name: load-test

on:
  push:
    paths:
      - 'load/k6-10k-tables.js'
      - 'load/k6-ws-packet-loss.js'
      - '.github/workflows/load-test.yml'
  pull_request:
    paths:
      - 'load/k6-10k-tables.js'
      - 'load/k6-ws-packet-loss.js'
      - '.github/workflows/load-test.yml'

jobs:
  k6-load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run k6 10k tables scenario
        run: node load/k6-10k-tables.js --summary-export=summary-tables.json --summary-trend-stats="avg,med,min,max,p(95),p(99)" --out json=metrics-tables.json
      - name: Run k6 ws packet loss scenario
        run: node load/k6-ws-packet-loss.js --summary-export=summary-ws.json --summary-trend-stats="avg,med,min,max,p(95),p(99)" --out json=metrics-ws.json
      - name: Check latency thresholds
        run: |
          p95_tables=$(jq '.metrics.ack_latency["p(95)"]' summary-tables.json)
          p95_ws=$(jq '.metrics.ws_latency["p(95)"]' summary-ws.json)
          status=0
          if (( $(echo "$p95_tables > 120" | bc -l) )); then
            echo "10k tables p95 $p95_tables ms exceeds 120ms"; status=1
          fi
          if (( $(echo "$p95_ws > 120" | bc -l) )); then
            echo "ws packet loss p95 $p95_ws ms exceeds 120ms"; status=1
          fi
          exit $status
      - name: Upload k6 artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: k6-load-test
          path: |
            summary-tables.json
            metrics-tables.json
            summary-ws.json
            metrics-ws.json
