name: nightly-load-test

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  chaos-10k:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install k6 and Artillery
        run: npm install -g k6 artillery

      - name: Run 10k chaos load test
        run: |
          ./load/run-10k-chaos.sh --sockets 100 --packet-loss 0.01 --jitter 50

      - name: Archive metrics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: chaos-metrics
          path: load/metrics/latest
