name: load-regression

on:
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest
    env:
      DR_DRILL_SLA_DAYS: 7
      DR_FAILOVER_SLA_DAYS: 30
      DR_RESTORE_SLA_DAYS: 30
      DR_THROWAWAY_SLA_DAYS: 7
      SOAK_SLA_HOURS: 24
    steps:
      - uses: ./.github/actions/ops-preflight
        with:
          slack-channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          soak-metrics-sla-hours: ${{ env.SOAK_SLA_HOURS }}
          dr-drill-sla-days: ${{ env.DR_DRILL_SLA_DAYS }}
          dr-failover-sla-days: ${{ env.DR_FAILOVER_SLA_DAYS }}
          dr-restore-sla-days: ${{ env.DR_RESTORE_SLA_DAYS }}
          dr-throwaway-sla-days: ${{ env.DR_THROWAWAY_SLA_DAYS }}

  tables-10k:
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run 10k table scenario
        uses: grafana/k6-action@v0.2.0
        with:
          filename: load/k6-10k-tables.js
          flags: --summary-export=10k-summary.json
      - name: Check thresholds
        run: ./load/check-thresholds.sh 10k-summary.json
      - name: Upload summary
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tables-10k-summary
          path: 10k-summary.json

  packet-loss:
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run packet loss scenario
        uses: grafana/k6-action@v0.2.0
        with:
          filename: load/k6-ws-packet-loss.js
          flags: --summary-export=packet-summary.json
      - name: Check thresholds
        run: ./load/check-thresholds.sh packet-summary.json
      - name: Upload summary
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: packet-loss-summary
          path: packet-summary.json

  chaos-regression:
    needs: preflight
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - network-latency.yaml
          - pod-kill.yaml
    steps:
      - uses: actions/checkout@v4
      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
      - name: Apply chaos scenario
        uses: chaos-mesh/chaos-mesh-action@master
        env:
          CFG_FILE: infra/tests/load/chaos/${{ matrix.scenario }}
          CHAOS_MESH_VERSION: v2.6.0
      - name: Run k6 chaos scenario
        uses: grafana/k6-action@v0.2.0
        with:
          filename: load/k6-10k-tables.js
          flags: --summary-export=chaos-${{ matrix.scenario }}.json
      - name: Check thresholds
        run: ./load/check-thresholds.sh chaos-${{ matrix.scenario }}.json
      - name: Upload summary
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: chaos-${{ matrix.scenario }}-summary
          path: chaos-${{ matrix.scenario }}.json
