name: ops-artifacts-verify

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      PROOF_ARCHIVE_BUCKET: ${{ secrets.PROOF_ARCHIVE_BUCKET }}
      SPECTATOR_PRIVACY_BUCKET: ${{ secrets.SPECTATOR_PRIVACY_BUCKET }}
      SOAK_TRENDS_BUCKET: ${{ secrets.SOAK_TRENDS_BUCKET }}

      RUN_ID: ${{ github.run_id }}
      DR_METRICS_BUCKET: ${{ secrets.DR_METRICS_BUCKET }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci --legacy-peer-deps
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
      - name: Get spectator privacy run ID
        id: get_run_id
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e
          RUN_ID=$(gh api \
            repos/${{ github.repository }}/actions/workflows/spectator-privacy-nightly.yml/runs \
            --jq '.workflow_runs[0].id // empty')
          if [ -z "$RUN_ID" ]; then
            echo "No spectator-privacy-nightly run found" >&2
            exit 1
          fi
          echo "RUN_ID=$RUN_ID" >> "$GITHUB_OUTPUT"
        - name: Verify ops artifacts
          env:
            RUN_ID: ${{ steps.get_run_id.outputs.RUN_ID }}
          run: |
            set +e
            out=$(npx ts-node scripts/verify-ops-artifacts.ts 2>&1)
            status=$?
            set -e
            echo "$out"
            printf "%s\n" "$out" > verify-ops.log
            printf "%s" "$out" | sha256sum >> verify-ops.log
            gcloud storage cp verify-ops.log gs://$DR_METRICS_BUCKET/verify/$GITHUB_RUN_ID/
            url="https://storage.googleapis.com/$DR_METRICS_BUCKET/verify/$GITHUB_RUN_ID/verify-ops.log"
            echo "$url" >> "$GITHUB_STEP_SUMMARY"
            exit $status
