name: pitr-nightly

on:
  schedule:
    - cron: '15 1 * * *'
  workflow_dispatch:

jobs:
  pitr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run nightly PITR backup
        run: bash infra/disaster-recovery/tests/pitr-nightly.sh | tee pitr-nightly.log
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PG_INSTANCE_ID: ${{ vars.PG_INSTANCE_ID }}
          CLICKHOUSE_BUCKET: ${{ vars.CLICKHOUSE_BUCKET }}
          SECONDARY_REGION: ${{ vars.SECONDARY_REGION }}
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pitr-nightly
          path: pitr-nightly.log
      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            { "text": "Nightly PITR backup failed for ${GITHUB_REPOSITORY}@${GITHUB_SHA}" }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
