name: proof-archive-audit
concurrency:
  group: "proof-archive-audit"
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-proof-archive:
    runs-on: ubuntu-latest
    env:
      PROOF_ARCHIVE_BUCKET: ${{ secrets.PROOF_ARCHIVE_BUCKET }}
      PROOF_ARCHIVE_EXPECTED_DAILY_COUNT: ${{ vars.PROOF_ARCHIVE_EXPECTED_DAILY_COUNT }}
      SECONDARY_REGION: ${{ vars.SECONDARY_REGION }}
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx -y ts-node scripts/check-proof-archive.ts
      - run: npx -y ts-node scripts/check-proof-archive-replication.ts
      - name: Record audit success metric
        if: success()
        run: gcloud monitoring metrics write custom.googleapis.com/proof/archive_audit_success 1
      - name: Record audit failure metric
        if: failure()
        run: gcloud monitoring metrics write custom.googleapis.com/proof/archive_audit_success 0
