name: release

on:
  release:
    types: [published]

jobs:
  spectator-privacy:
    uses: ./.github/workflows/spectator-privacy.yml
    secrets: inherit

  soak:
    uses: ./.github/workflows/soak.yml
    secrets: inherit

  failover-drill:
    uses: ./.github/workflows/failover-drill.yml
    secrets: inherit

  proof-archive:
    uses: ./.github/workflows/proof-archive.yml
    secrets: inherit

  publish-docs:
    needs:
      - spectator-privacy
      - soak
      - failover-drill
      - proof-archive
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Verify prerequisite workflows
        run: |
          if [ "${{ needs.spectator-privacy.result }}" != "success" ] || \
             [ "${{ needs.soak.result }}" != "success" ] || \
             [ "${{ needs.failover-drill.result }}" != "success" ] || \
             [ "${{ needs.proof-archive.result }}" != "success" ]; then
            echo "One or more prerequisite workflows failed." >&2
            exit 1
          fi
      - uses: actions/checkout@v4
      - name: Inject release tag
        run: |
          sed -i "s/{{RELEASE_TAG}}/${{ github.ref_name }}/" docs/player/README.md
      - name: Upload player docs
        uses: actions/upload-artifact@v4
        with:
          name: player-docs-${{ github.ref_name }}
          path: docs/player
