name: restore-latest
concurrency:
  group: "restore-latest"
  cancel-in-progress: true

on:
  schedule:
  - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  check-proof-archive:
    if: ${{ always() }}
    uses: ./.github/workflows/check-proof-archive.yml
    secrets: inherit
  dr-sla:
    needs: check-proof-archive
    uses: ./.github/workflows/dr-sla.yml
    secrets: inherit
    with:
      dr-drill-sla-days: 30
  restore-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - name: Restore latest snapshot
      run: bash infra/disaster-recovery/restore-latest.sh | tee 
        restore-latest.log
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        PG_PRIMARY_ID: ${{ vars.PG_PRIMARY_ID }}
        SECONDARY_REGION: ${{ vars.SECONDARY_REGION }}
        PGUSER: ${{ vars.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGDATABASE: postgres
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: restore-latest-${{ github.sha }}
        path: |
          restore-latest.log
          infra/disaster-recovery/restore-latest.metrics
    - name: PagerDuty alert on failure
      if: failure()
      env:
        ROUTING_KEY: ${{ secrets.PAGERDUTY_ROUTING_KEY }}
      run: |
        curl -X POST https://events.pagerduty.com/v2/enqueue \
          -H 'Content-Type: application/json' \
          -d '{"routing_key":"'$ROUTING_KEY'","event_action":"trigger","payload":{"summary":"Latest backup restore failed","source":"github-actions","severity":"error","custom_details":{"runbook":"https://github.com/Nera26/pokerhub/blob/main/docs/runbooks/disaster-recovery.md"}}}'

    needs:
    - dr-sla
    - check-proof-archive
  soak-metrics:
    needs:
    - dr-sla
    - restore-latest
    - check-proof-archive
    if: ${{ always() }}
    uses: ./.github/workflows/soak-metrics.yml
    secrets: inherit

  spectator-privacy:
    needs:
    - dr-sla
    - restore-latest
    - soak-metrics
    - check-proof-archive
    if: ${{ always() }}
    uses: ./.github/workflows/spectator-privacy.yml
    secrets: inherit
    with:
      logs: restore-latest.log
