name: Security Scan

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ secrets.DEV_SERVER_URL }}
          allow_issue_writing: false
          cmd_options: '-a -J zap-report.json'
      - name: Fail on ASVS L2 or high findings
        run: |
          if jq '.site[].alerts[] | select((.riskcode | tonumber) >= 2)' zap-report.json | grep -q .; then
            echo 'High/critical or ASVS L2 vulnerabilities found'
            exit 1
          else
            echo 'No ASVS L2 or high findings'
          fi
