---
"on":
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

name: soak-test

jobs:
  soak:
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    env:
      METRICS_URL: http://localhost:3000/metrics
    steps:
      - uses: actions/checkout@v4
      - name: Install toxiproxy CLI
        run: |
          TOXI_VER=v2.5.0
          TOXI_BASE=https://github.com/Shopify/toxiproxy/releases/download/$TOXI_VER
          curl -sSL $TOXI_BASE/toxiproxy-cli-linux-amd64 \
            -o /usr/local/bin/toxiproxy-cli
          chmod +x /usr/local/bin/toxiproxy-cli
      - name: Start toxiproxy
        run: |
          docker run -d --name toxiproxy -p 8474:8474 -p 3001:3001 \
            ghcr.io/shopify/toxiproxy
      - name: Configure toxiproxy
        run: load/toxiproxy-soak.sh
        env:
          PROXY_PORT: 3001
          UPSTREAM: localhost:3000
      - name: Start GC/heap collector
        run: |
          load/collect-gc-heap.sh &
          echo $! > collector.pid
        env:
          GRAFANA_PUSH_URL: ${{ secrets.GRAFANA_PUSH_URL }}
      - name: Run k6 soak test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: load/k6-ws-soak.js
          flags: >-
            --summary-export=soak-summary.json
            -o experimental-prometheus-rw=${{ secrets.GRAFANA_PROM_URL }}
      - name: Stop GC/heap collector
        if: always()
        run: kill $(cat collector.pid)
      - name: Stop toxiproxy
        if: always()
        run: docker rm -f toxiproxy
      - name: Upload summary
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: soak-summary
          path: soak-summary.json
      - name: Upload GC metrics
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: gc-heap-metrics
          path: gc-heap-metrics.log
