---
"on":
  workflow_call:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

name: soak-metrics

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
      - id: check
        run: npx ts-node scripts/check-soak-metrics.ts
      - name: Analyze soak trends
        run: npx ts-node scripts/analyze-soak-trends.ts metrics/
      - name: Prepare regression alert
        if: steps.check.outcome == 'failure'
        env:
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        run: |
          msg=$(jq -r '.regressions[].message' soak-regression.json | paste -sd '; ' -)
          jq -n --arg channel "$SLACK_CHANNEL_ID" --arg text "Soak metrics regression detected: $msg" '{channel:$channel, text:$text}' > slack.json
          printf "Soak metrics regression detected\n\n\`\`\`\n%s\n\`\`\`\n" "$(cat soak-regression.json)" > soak-regression.md
      - name: Slack alert
        if: steps.check.outcome == 'failure'
        uses: slackapi/slack-github-action@v1
        with:
          method: chat.postMessage
          payload-file-path: slack.json
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Open soak regression issue
        if: steps.check.outcome == 'failure'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "SLA breached: soak metrics"
          content-filepath: soak-regression.md
      - name: Upload soak summary
        if: always() && hashFiles('soak-summary.json') != ''
        uses: actions/upload-artifact@v4
        with:
          name: soak-summary
          path: soak-summary.json
      - name: Load soak summary to BigQuery
        if: always() && hashFiles('soak-summary.json') != ''
        run: |
          bq load --source_format=NEWLINE_DELIMITED_JSON --autodetect ops_metrics.soak_trends soak-summary.json
