name: soak-test

on:
  workflow_dispatch:

jobs:
  soak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run k6 soak test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: infra/tests/load/k6-soak.js
          arguments: --summary-export=soak-summary.json
      - name: Upload summary
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: soak-summary
          path: soak-summary.json
