name: spectator-privacy

on:
  pull_request:
    # Run spectator privacy checks on every pull request

jobs:
  spectator-privacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
      - uses: ./.github/actions/spectator-privacy-check
      - name: Sanitize logs
        if: always()
        run: npx ts-node scripts/sanitize-spectator-logs.ts backend-tests.log frontend-tests.log
      - name: DLP scan logs
        if: always()
        env:
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
        run: npx ts-node scripts/dlp-scan.ts backend-tests.log frontend-tests.log
      - name: Verify sanitized logs
        if: always()
        run: |
          if rg -i "userId|tableSecret|sessionToken|email|ipAddress" backend-tests.log frontend-tests.log; then
            echo "PII found in logs" >&2
            exit 1
          fi
      - name: Upload logs as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spectator-privacy-logs
          path: |
            backend-tests.log
            frontend-tests.log
            dlp-scan.json
          retention-days: 14
