name: spectator-privacy-nightly
concurrency:
  group: "spectator-privacy-nightly"
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  spectator-privacy:
    env:
      PROD_LOG_SCAN: true
    uses: ./.github/workflows/spectator-privacy.yml
    secrets: inherit
    with:
      logs: backend-tests.log frontend-tests.log integration.log property.log

  check-proof-archive:
    needs: spectator-privacy
    if: ${{ always() }}
    uses: ./.github/workflows/check-proof-archive.yml
    secrets: inherit
