name: spectator-privacy-nightly

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  spectator-privacy:
    runs-on: ubuntu-latest
    env:
      SPECTATOR_PRIVACY_BUCKET: ${{ secrets.SPECTATOR_PRIVACY_BUCKET }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: ./.github/actions/spectator-privacy-check
      - name: Upload logs to S3
        if: always()
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          aws s3 cp backend-tests.log s3://$SPECTATOR_PRIVACY_BUCKET/$RUN_ID/backend-tests.log
          aws s3 cp frontend-tests.log s3://$SPECTATOR_PRIVACY_BUCKET/$RUN_ID/frontend-tests.log
      - name: Upload logs as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spectator-privacy-logs
          path: |
            backend-tests.log
            frontend-tests.log
          retention-days: 14
      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            { "text": "Spectator privacy nightly tests failed for ${GITHUB_REPOSITORY}@${GITHUB_SHA}" }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
