name: spectator-privacy

on:
  pull_request:
    # Run spectator privacy checks on every pull request

jobs:
  spectator-privacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/spectator-privacy-check
      - name: Sanitize logs
        if: always()
        run: npx ts-node scripts/sanitize-spectator-logs.ts backend-tests.log frontend-tests.log
      - name: Verify sanitized logs
        if: always()
        run: |
          if rg -i "userId|tableSecret" backend-tests.log frontend-tests.log; then
            echo "PII found in logs" >&2
            exit 1
          fi
      - name: Upload logs as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spectator-privacy-logs
          path: |
            backend-tests.log
            frontend-tests.log
          retention-days: 14
