name: ws-ack-threshold

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ws-ack-threshold]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate WebSocket ACK latency
        run: |
          ack=${{ github.event.client_payload.ws_ack_ms || 0 }}
          threshold=250
          echo "WebSocket ACK latency: $ack ms (threshold $threshold ms)"
          if [ "$ack" -gt "$threshold" ]; then
            echo "SLO breach: ACK latency exceeds threshold" >&2
            exit 1
          fi
